import { Certification } from '../types/certifications';

export const defaultCertification: Certification[] = [
    {
        name: 'IATF 16949:2016',
        image: '/images/Advanced.jpg',
        url: '#',
        code: 'IATF-16949',
        issuer: 'TÜV Rheinland',
        validUntil: '2026-05',
        scope: 'Quality Management System for Automotive Production',
        status: 'valid',
        issueDate: '2021-05',
        lastAudit: '2023-06',
    },
    {
        name: 'ISO 9001:2015',
        image: '/images/Aluminum.jpg',
        url: '#',
        code: 'ISO-9001',
        issuer: 'TÜV Rheinland',
        validUntil: '2025-10',
        scope: 'Quality Management System for Manufacturing',
        status: 'valid',
        issueDate: '2020-10',
        lastAudit: '2023-04',
    },
    {
        name: 'ISO 14001:2015',
        image: '/images/cnc.jpg',
        url: '#',
        code: 'ISO-14001',
        issuer: 'TÜV Rheinland',
        validUntil: '2025-10',
        scope: 'Environmental Management System',
        status: 'valid',
        issueDate: '2020-10',
        lastAudit: '2023-04',
    },
    {
        name: 'PPAP Level 3 Approval',
        image: '/images/Material-3.jpg',
        url: '#',
        code: 'PPAP-L3',
        issuer: 'Global OEM',
        validUntil: 'Continuous',
        scope: 'Production Part Approval Process',
        status: 'valid',
        issueDate: '2022-03',
        lastAudit: '2023-08',
    },
    {
        name: 'Eco-friendly Manufacturing',
        image: '/images/Material-2.jpg',
        url: '#',
        code: 'GREEN-MFG',
        issuer: 'Industry Alliance',
        validUntil: '2024-12',
        scope: 'Environmental Standards for Aluminum Processing',
        status: 'pending-renewal',
        issueDate: '2021-12',
        lastAudit: '2023-01',
    },
];
