import { Product } from '../types/product';

export const DEFAULT_PRODUCTS: Product[] = [
    {
        name: 'AL. Wheel',
        description: 'Precision-engineered aluminum wheels with superior strength-to-weight ratio',
        image: '/images/Material-1.jpg',
        category: 'Automotive',
        applications: 'Cars, SUVs, Motorcycles',
        material: 'A356/ADC12',
        weight: '30% Lighter',
        techCode: 'AW-356-11',
        precision: '±0.05mm',
        compatibility: 95,
        strength: 88,
    },
    {
        name: 'Light-Weight Products',
        description: 'Ultra-lightweight aluminum components reducing vehicle weight and emissions',
        image: '/images/Material-2.jpg',
        category: 'Automotive',
        applications: 'EV Battery Housing, Structural Components',
        material: 'A380/ADC12',
        weight: '40% Lighter',
        techCode: 'LW-380-23',
        precision: '±0.02mm',
        compatibility: 92,
        strength: 85,
    },
    {
        name: 'Green Energy Products',
        description: 'Sustainable aluminum solutions for renewable energy applications',
        image: '/images/Material-3.jpg',
        category: 'Energy',
        applications: 'Solar Mounting, Wind Turbine Components',
        material: 'A383/A380',
        weight: '25% Energy Efficient',
        techCode: 'GE-383-17',
        precision: '±0.08mm',
        compatibility: 90,
        strength: 92,
    },
    {
        name: 'Agricultural Products',
        description: 'Durable aluminum components for agricultural machinery and equipment',
        image: '/images/Material-1.jpg',
        category: 'Agriculture',
        applications: 'Irrigation Systems, Equipment Parts',
        material: 'ADC12/A356',
        weight: '35% More Durable',
        techCode: 'AG-356-09',
        precision: '±0.1mm',
        compatibility: 88,
        strength: 94,
    },
];
